version: '3'

services:
  nats-server:
    image: nats:latest
    ports:
      - "8222:8222"
  client-gateway:
    build: ./client-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
  auth-db:
    container_name: auth-db
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    environment:
      MONGO_INITDB_DATABASE: auth-db
    volumes:
      - ./mongo:/data/db
  auth-ms:
    depends_on:
      - auth-db
    build: ./auth-ms
    volumes:
      - ./auth-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3004
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=mongodb://auth-db:27017/auth-db?replicaSet=rs0
      - JWT_SECRETE=estoDebeDeSerUnStringSeguro
 
  products-ms:
    build: ./products-ms
    volumes:
      - ./products-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db    

  orders-db:
    container_name: orders_database
    image: postgres:16.2
    restart: always
    volumes: 
     - ./orders-ms/postgres:/var/lib/postgresql/orders_database
    ports:
     - 5432:5432
    environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: 123456
     POSTGRES_DB: ordersdb
  
  orders-ms:
    depends_on:
      - orders-db
    build: ./orders-ms
    volumes:
      - ./orders-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3002
      - DATABASE_URL=postgresql://postgres:123456@orders-db:5432/ordersdb?schema=public
      - NATS_SERVERS=nats://nats-server:4222
  payments-ms:
    build: ./payments-ms
    volumes:
      - ./payments-ms/src:/usr/src/app/src
    ports:
     - 3003:3003
    command: npm run start:dev
    environment:
      - PORT=3003
      - STRIPE_SECRET=sk_test_51R3iIuEd6mWG0zbHS0ZKoGnaR34NJ9ldsTnIjQ2ZrbAgX4QrXHQtPgDYz2zpUT7LzHVjS8opGx9hz4jpcxpEBfgj00fe1xLCb0
      - STRIPE_SUCCESS_URL=http://localhost:3003/payments/success
      - STRIPE_CANCEL_URL=http://localhost:3003/payments/success
      - STRIPE_ENPOINTSECRET=whsec_elQamddf1uLrF8GAqStpI76k3dI9dfVe
      - NATS_SERVERS=nats://nats-server:4222


  